"use client";
import { useEffect,useMemo,useState } from "react";
import { useRouter } from "next/navigation";
import { createClient } from "../../lib/supabase/client";
type C={id:string;name:string;phone:string|null;email:string|null;status:string|null;created_at:string};
export default function CustomersPage(){const r=useRouter(),s=useMemo(()=>createClient(),[]);const [x,setX]=useState<C[]>([]),[q,setQ]=useState(""),[open,setOpen]=useState(false),[name,setName]=useState(""),[phone,setPhone]=useState(""),[email,setEmail]=useState(""),[err,setErr]=useState(""),[org,setOrg]=useState<string|null>(null);
async function load(){const {data:{user}}=await s.auth.getUser();if(!user){r.replace("/login");return}const id=localStorage.getItem("bizos_org_id");if(!id){r.replace("/onboarding");return}setOrg(id);const {data,error}=await s.from("customers").select("id,name,phone,email,status,created_at").eq("organization_id",id).order("created_at",{ascending:false});if(error)setErr(error.message);else setX(data||[])}useEffect(()=>{load()},[]);
async function add(e:React.FormEvent){e.preventDefault();if(!org)return;const {error}=await s.from("customers").insert({organization_id:org,name:name.trim(),phone:phone||null,email:email||null});if(error)setErr(error.message);else{setName("");setPhone("");setEmail("");setOpen(false);load()}}
async function del(id:string){if(!confirm("Delete this customer?"))return;const {error}=await s.from("customers").delete().eq("id",id).eq("organization_id",org);if(error)setErr(error.message);else setX(v=>v.filter(c=>c.id!==id))}
const list=x.filter(c=>[c.name,c.phone,c.email].join(" ").toLowerCase().includes(q.toLowerCase()));
return <main className="min-h-screen bg-[#05070b] text-white"><div className="mx-auto max-w-6xl px-5 py-8"><button onClick={()=>r.push("/")} className="text-xs text-cyan-300">← Overview</button><div className="mt-6 flex justify-between gap-4"><div><div className="text-[10px] tracking-[.2em] text-cyan-400">RELATIONSHIP LAYER</div><h1 className="mt-2 text-4xl font-semibold">Customers.</h1><p className="mt-2 text-sm text-white/40">Every relationship in one live workspace.</p></div><button onClick={()=>setOpen(true)} className="h-fit rounded-xl bg-cyan-400 px-5 py-3 text-sm font-bold text-black">+ New customer</button></div>{err&&<div className="mt-5 rounded-xl border border-red-400/20 bg-red-400/5 p-4 text-xs text-red-300">{err}</div>}<input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search customers…" className="mt-6 w-full rounded-2xl border border-white/10 bg-white/[.025] px-4 py-4 text-sm outline-none"/><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{list.map(c=><div key={c.id} className="rounded-2xl border border-white/10 bg-white/[.025] p-5"><div className="flex justify-between"><div><div className="font-medium">{c.name}</div><div className="mt-1 text-xs text-white/35">{c.phone||c.email||"No contact"}</div></div><button onClick={()=>del(c.id)} className="text-xs text-red-300/50">Delete</button></div><div className="mt-5 text-xs text-cyan-300">{c.status||"active"}</div></div>)}</div>{!list.length&&<div className="mt-4 rounded-3xl border border-dashed border-white/10 p-14 text-center text-sm text-white/40">No customers found.</div>}</div>{open&&<div className="fixed inset-0 z-50 grid place-items-center bg-black/70 p-5"><form onSubmit={add} className="w-full max-w-lg rounded-3xl border border-white/10 bg-[#0a0d12] p-6"><div className="flex justify-between"><h2 className="text-xl font-semibold">New customer</h2><button type="button" onClick={()=>setOpen(false)}>✕</button></div><div className="mt-6 space-y-4">{[["Name",name,setName,"text"],["Phone",phone,setPhone,"tel"],["Email",email,setEmail,"email"]].map(([l,v,set,t])=><label key={l as string} className="block text-xs text-white/45">{l as string}<input required={l==="Name"} type={t as string} value={v as string} onChange={e=>(set as Function)(e.target.value)} className="mt-2 w-full rounded-xl border border-white/10 bg-black/20 px-4 py-3 text-sm"/></label>)}</div><button className="mt-6 w-full rounded-xl bg-cyan-400 py-3 font-bold text-black">Create customer →</button></form></div>}</main>}